name: .NET

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - README.md
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
env:
  AZURE_RG: github-action-staged
  AZURE_SUBSCRIPTION: 579a5ec5-808f-4c5c-92b7-212ee4aa8ba0
  AZURE_LOCATION: westeurope

jobs:
  Build-Job:
    runs-on: ubuntu-latest
    env:
      configuration: release
    steps:
    - name: Check Sources
    - uses: actions/checkout@v2
    - name: Setup .NET.
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration ${{env.configuration}}
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration ${{env.configuration} --output ${{runner.temp}}/publish}
